security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: plaintext

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Etudiant
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        login:
            pattern: ^/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /login
                username_path: login
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern: ^/
            provider: app_user_provider
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_ETUDIANT }

when@dev:
    security:
        firewalls:
            main:
                pattern: ^/
                stateless: true
                provider: app_user_provider
                security: false  # ← désactive toute sécurité sur ce firewall en dev